# Generated by Django 3.0.3 on 2020-06-21 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200531_1516'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_edit_records', 'Add, edit, delete Author records'),)},
        ),
    ]
